apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat8-jvm
  labels:
    version: 8.5.56
    env: test
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      version: 8.5.56
      env: test
  template:
    metadata:
      name: tomcat8-pipeline
      labels:
        version: 8.5.56
        env: test
      annotations:
        prometheus_io_scrape: "true"
        prometheus_io_port: "12346"
        prometheus_io_path: /
        blackbox_port: "8080"
        blackbox_scheme: http
        blackbox_path: /
    spec:
      containers:
      - name: tomcat
        image: imageName
        imagePullPolicy: IfNotPresent
        ports:
        - name: tomcat
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
      imagePullSecrets:
      - name: harbor
